### ISSUE TITLE
Suggestion: Change body bg color

### ISSUE THREAD

**Issue by WilliamFerns1** [Mitanshu21/react-calculator#6]
I think it looks better if the main body is a different color

### The index.css style could be changed to this: 

```css
// Body:
  body {
    margin: 0;
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen',
      'Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans', 'Helvetica Neue',
      sans-serif;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    background-color: red; // This line is changed
}

```

***Note, this is just a dummy issue, I am following a course on how Git and Github works. You can ignore this***
